theme: jekyll-theme-minimal
title: David Biertimpel
logo: ./assets/portrait.jpg
author: David Biertimpel
baseurl: ""
description: [CV](https://github.com/dbtmpl/Curriculum-Vitae)
profile_url: "https://dbtmpl.github.io/"
# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge